export {default as solar__skyscraper} from "./solar-skyscraper.png";
export {default as company__photo} from "./company_photo.jpeg";
export {default as panel} from "./panel.jpeg";
export {default as turbine} from "./turbine.jpeg";
export {default as batteries} from "./batteries.jpeg";
export {default as member1 } from "./member-1.jpeg";
export {default as member2 } from "./member-2.jpeg";
export {default as member3 } from "./member-3.jpeg";
export {default as member4 } from "./member-4.jpeg";
export {default as profile1} from "./profile-1.png";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";